<?php

return [
	['timezone' => 'Pacific/Midway', 'name' => '(UTC-11:00) Midway Island'],
	['timezone' => 'US/Samoa', 'name' => '(UTC-11:00) Samoa'],
	['timezone' => 'US/Hawaii', 'name' => '(UTC-10:00) Hawaii'],
	['timezone' => 'US/Alaska', 'name' => '(UTC-09:00) Alaska'],
	['timezone' => 'US/Pacific', 'name' => '(UTC-08:00) Pacific Time (US &amp; Canada)'],
	['timezone' => 'America/Tijuana', 'name' => '(UTC-08:00) Tijuana'],
	['timezone' => 'US/Arizona', 'name' => '(UTC-07:00) Arizona'],
	['timezone' => 'US/Mountain', 'name' => '(UTC-07:00) Mountain Time (US &amp; Canada)'],
	['timezone' => 'America/Chihuahua', 'name' => '(UTC-07:00) Chihuahua'],
	['timezone' => 'America/Mazatlan', 'name' => '(UTC-07:00) Mazatlan'],
	['timezone' => 'America/Mexico_City', 'name' => '(UTC-06:00) Mexico City'],
	['timezone' => 'America/Monterrey', 'name' => '(UTC-06:00) Monterrey'],
	['timezone' => 'Canada/Saskatchewan', 'name' => '(UTC-06:00) Saskatchewan'],
	['timezone' => 'US/Central', 'name' => '(UTC-06:00) Central Time (US &amp; Canada)'],
	['timezone' => 'US/Eastern', 'name' => '(UTC-05:00) Eastern Time (US &amp; Canada)'],
	['timezone' => 'US/East-Indiana', 'name' => '(UTC-05:00) Indiana (East)'],
	['timezone' => 'America/Bogota', 'name' => '(UTC-05:00) Bogota'],
	['timezone' => 'America/Lima', 'name' => '(UTC-05:00) Lima'],
	['timezone' => 'America/Caracas', 'name' => '(UTC-04:30) Caracas'],
	['timezone' => 'Canada/Atlantic', 'name' => '(UTC-04:00) Atlantic Time (Canada)'],
	['timezone' => 'America/La_Paz', 'name' => '(UTC-04:00) La Paz'],
	['timezone' => 'America/Santiago', 'name' => '(UTC-04:00) Santiago'],
	['timezone' => 'Canada/Newfoundland', 'name' => '(UTC-03:30) Newfoundland'],
	['timezone' => 'America/Buenos_Aires', 'name' => '(UTC-03:00) Buenos Aires'],
	['timezone' => 'Greenland', 'name' => '(UTC-03:00) Greenland'],
	['timezone' => 'Atlantic/Stanley', 'name' => '(UTC-02:00) Stanley'],
	['timezone' => 'Atlantic/Azores', 'name' => '(UTC-01:00) Azores'],
	['timezone' => 'Atlantic/Cape_Verde', 'name' => '(UTC-01:00) Cape Verde Is.'],
	['timezone' => 'Africa/Casablanca', 'name' => '(UTC-00:00) Casablanca'],
	['timezone' => 'Europe/Dublin', 'name' => '(UTC-00:00) Dublin'],
	['timezone' => 'Europe/Lisbon', 'name' => '(UTC-00:00) Lisbon'],
	['timezone' => 'Europe/London', 'name' => '(UTC-00:00) London'],
	['timezone' => 'Africa/Monrovia', 'name' => '(UTC-00:00) Monrovia'],
	['timezone' => 'Europe/Amsterdam', 'name' => '(UTC+01:00) Amsterdam'],
	['timezone' => 'Europe/Belgrade', 'name' => '(UTC+01:00) Belgrade'],
	['timezone' => 'Europe/Berlin', 'name' => '(UTC+01:00) Berlin'],
	['timezone' => 'Europe/Bratislava', 'name' => '(UTC+01:00) Bratislava'],
	['timezone' => 'Europe/Brussels', 'name' => '(UTC+01:00) Brussels'],
	['timezone' => 'Europe/Budapest', 'name' => '(UTC+01:00) Budapest'],
	['timezone' => 'Europe/Copenhagen', 'name' => '(UTC+01:00) Copenhagen'],
	['timezone' => 'Europe/Ljubljana', 'name' => '(UTC+01:00) Ljubljana'],
	['timezone' => 'Europe/Madrid', 'name' => '(UTC+01:00) Madrid'],
	['timezone' => 'Europe/Paris', 'name' => '(UTC+01:00) Paris'],
	['timezone' => 'Europe/Prague', 'name' => '(UTC+01:00) Prague'],
	['timezone' => 'Europe/Rome', 'name' => '(UTC+01:00) Rome'],
	['timezone' => 'Europe/Sarajevo', 'name' => '(UTC+01:00) Sarajevo'],
	['timezone' => 'Europe/Skopje', 'name' => '(UTC+01:00) Skopje'],
	['timezone' => 'Europe/Stockholm', 'name' => '(UTC+01:00) Stockholm'],
	['timezone' => 'Europe/Vienna', 'name' => '(UTC+01:00) Vienna'],
	['timezone' => 'Europe/Warsaw', 'name' => '(UTC+01:00) Warsaw'],
	['timezone' => 'Europe/Zagreb', 'name' => '(UTC+01:00) Zagreb'],
	['timezone' => 'Europe/Athens', 'name' => '(UTC+02:00) Athens'],
	['timezone' => 'Europe/Bucharest', 'name' => '(UTC+02:00) Bucharest'],
	['timezone' => 'Africa/Cairo', 'name' => '(UTC+02:00) Cairo'],
	['timezone' => 'Africa/Harare', 'name' => '(UTC+02:00) Harare'],
	['timezone' => 'Europe/Helsinki', 'name' => '(UTC+02:00) Helsinki'],
	['timezone' => 'Europe/Istanbul', 'name' => '(UTC+02:00) Istanbul'],
	['timezone' => 'Asia/Jerusalem', 'name' => '(UTC+02:00) Jerusalem'],
	['timezone' => 'Europe/Kiev', 'name' => '(UTC+02:00) Kyiv'],
	['timezone' => 'Europe/Riga', 'name' => '(UTC+02:00) Riga'],
	['timezone' => 'Europe/Sofia', 'name' => '(UTC+02:00) Sofia'],
	['timezone' => 'Europe/Tallinn', 'name' => '(UTC+02:00) Tallinn'],
	['timezone' => 'Europe/Vilnius', 'name' => '(UTC+02:00) Vilnius'],
	['timezone' => 'Asia/Baghdad', 'name' => '(UTC+03:00) Baghdad'],
	['timezone' => 'Asia/Kuwait', 'name' => '(UTC+03:00) Kuwait'],
	['timezone' => 'Europe/Minsk', 'name' => '(UTC+03:00) Minsk'],
	['timezone' => 'Africa/Nairobi', 'name' => '(UTC+03:00) Nairobi'],
	['timezone' => 'Asia/Riyadh', 'name' => '(UTC+03:00) Riyadh'],
	['timezone' => 'Europe/Moscow', 'name' => '(UTC+03:00) Moscow'],
	['timezone' => 'Asia/Tehran', 'name' => '(UTC+03:30) Tehran'],
	['timezone' => 'Asia/Baku', 'name' => '(UTC+04:00) Baku'],
	['timezone' => 'Europe/Volgograd', 'name' => '(UTC+04:00) Volgograd'],
	['timezone' => 'Asia/Muscat', 'name' => '(UTC+04:00) Muscat'],
	['timezone' => 'Asia/Tbilisi', 'name' => '(UTC+04:00) Tbilisi'],
	['timezone' => 'Asia/Yerevan', 'name' => '(UTC+04:00) Yerevan'],
	['timezone' => 'Asia/Kabul', 'name' => '(UTC+04:30) Kabul'],
	['timezone' => 'Asia/Karachi', 'name' => '(UTC+05:00) Karachi'],
	['timezone' => 'Asia/Tashkent', 'name' => '(UTC+05:00) Tashkent'],
	['timezone' => 'Asia/Kolkata', 'name' => '(UTC+05:30) Kolkata'],
	['timezone' => 'Asia/Kathmandu', 'name' => '(UTC+05:45) Kathmandu'],
	['timezone' => 'Asia/Yekaterinburg', 'name' => '(UTC+06:00) Ekaterinburg'],
	['timezone' => 'Asia/Almaty', 'name' => '(UTC+06:00) Almaty'],
	['timezone' => 'Asia/Dhaka', 'name' => '(UTC+06:00) Dhaka'],
	['timezone' => 'Asia/Novosibirsk', 'name' => '(UTC+06:00) Novosibirsk'],
	['timezone' => 'Asia/Bangkok', 'name' => '(UTC+07:00) Bangkok'],
	['timezone' => 'Asia/Jakarta', 'name' => '(UTC+07:00) Jakarta'],
	['timezone' => 'Asia/Krasnoyarsk', 'name' => '(UTC+07:00) Krasnoyarsk'],
	['timezone' => 'Asia/Chongqing', 'name' => '(UTC+08:00) Chongqing'],
	['timezone' => 'Asia/Hong_Kong', 'name' => '(UTC+08:00) Hong Kong'],
	['timezone' => 'Asia/Kuala_Lumpur', 'name' => '(UTC+08:00) Kuala Lumpur'],
	['timezone' => 'Australia/Perth', 'name' => '(UTC+08:00) Perth'],
	['timezone' => 'Asia/Singapore', 'name' => '(UTC+08:00) Singapore'],
	['timezone' => 'Asia/Taipei', 'name' => '(UTC+08:00) Taipei'],
	['timezone' => 'Asia/Ulaanbaatar', 'name' => '(UTC+08:00) Ulaan Bataar'],
	['timezone' => 'Asia/Urumqi', 'name' => '(UTC+08:00) Urumqi'],
	['timezone' => 'Asia/Irkutsk', 'name' => '(UTC+09:00) Irkutsk'],
	['timezone' => 'Asia/Seoul', 'name' => '(UTC+09:00) Seoul'],
	['timezone' => 'Asia/Tokyo', 'name' => '(UTC+09:00) Tokyo'],
	['timezone' => 'Australia/Darwin', 'name' => '(UTC+09:30) Darwin'],
	['timezone' => 'Asia/Yakutsk', 'name' => '(UTC+10:00) Yakutsk'],
	['timezone' => 'Australia/Brisbane', 'name' => '(UTC+10:00) Brisbane'],
	['timezone' => 'Pacific/Guam', 'name' => '(UTC+10:00) Guam'],
	['timezone' => 'Pacific/Port_Moresby', 'name' => '(UTC+10:00) Port Moresby'],
	['timezone' => 'Asia/Vladivostok', 'name' => '(UTC+10:00) Vladivostok'],
	['timezone' => 'Australia/Adelaide', 'name' => '(UTC+10:30) Adelaide'],
	['timezone' => 'Australia/Canberra', 'name' => '(UTC+11:00) Canberra'],
	['timezone' => 'Australia/Hobart', 'name' => '(UTC+11:00) Hobart'],
	['timezone' => 'Australia/Melbourne', 'name' => '(UTC+11:00) Melbourne'],
	['timezone' => 'Australia/Sydney', 'name' => '(UTC+11:00) Sydney'],
	['timezone' => 'Asia/Magadan', 'name' => '(UTC+12:00) Magadan'],
	['timezone' => 'Pacific/Auckland', 'name' => '(UTC+12:00) Auckland'],
	['timezone' => 'Pacific/Fiji', 'name' => '(UTC+12:00) Fiji'],
];